### PR TITLE
also use DEST_OS in cfg_cross_gnu

### PR DESCRIPTION
**Pull request by rpuntaie**
I've added an illustrative example + considered DEST_OS in the code

### CODE REVIEW

**Comment by ita1024** [comment]
There are lots of changes but I am not sure of the clarification value. And why `envar = os.environ.get(name) or conf.env.DEST_OS`?

**Comment by rpuntaie** [comment]
I've found that cfg_cross_gnu cannot be loaded together with gcc, because the latter will choose the local system as DEST_OS. So I had to do the configuration steps in gcc inside the wscript configure. I would like move these steps into cfg_cross_gnu, too. 

cross_gnu would be a better name. 

There should be a way to tell the cross_gnu tool the destination system inside wscript. I have chosen DEST_OS for this. This way one can compile for different DEST_OSes in one wscript via variants.

Of course, a better proposal is always welcome.

**Comment by rpuntaie** [comment]
I've done the mentioned changes.

**Comment by ita1024** [comment]
* `xcheck_envar` returns `DEST_OS` by default and that is the wrong place to do such a thing
* The docstrings now contain mixed indentation (both tabs and spaces)
* The docstrings contain project-specific flags of little documentation value

I could apply such changes but the above will be obliterated.

**Comment by rpuntaie** [comment]
fixed 1 and 2

regarding 3: fixed partially. I would like to keep the settings for Microchip PIC in the docstring in order for someone to find it, if he wants to compile with waf and
- to make up for not having a separate tool 
- as an example for other MCUs.

**Comment by ita1024** [comment]
The module is assuming gcc, but cross-compilation can also happen with g++, and with the clang family, so the `configure` function is incorrect.

**Comment by rpuntaie** [comment]
Since it is called cross_gnu, it should not include clang. gcc can also compile C++. I didn't add g++, because I had no need for it and it was not there in the first place. Many cross compilation tool chains don't include g++. Nevertheless one could and maybe should add g++ to cross_gnu.

**Comment by zougloub** [comment]
Hi, sorry guys I was attending some personal stuff (and still am), but here are some concerns of mine:
- These changes are breaking the API of the module which may be used in the wild (well, at least by me);
- Some lines of the patch are not changing anything;
- The "cfg" naming was considering that the module contains functions used for configuration (like its friend `cfg_altoptions`) and the intent was that to allow maximum flexibility vs. hard-coding a particular way of doing things;
- The "gnu" naming is coming from the name of the environment variables that are used, not relating to the compiler, and it was specifically supporting clang (from the docstring).

I would advise to split the module so the specialization is done by the `cross_gnu` tool while the free functions are in `cfg_cross_gnu`.

**Comment by rpuntaie** [comment]
Generally one can not have eternally the same interface, because it would block the evolution of a system.

The idea of tools in WAF is to load them in `configure()`. cfg_cross_gnu did not do that.

The interface of the functions have been extended in a backward compatible way.
It is just that now `configure()` is called when you load the tool inside the wscript `configure()`.
If you don't want that you can do an import at the top of wscript.

Through these changes the usefulness of this tool has been extended immensely.

Since the name of the tool ends in `_gnu`, the user expects it to be for gnu tools.
Nevertheless this interface has not changed and you can continue to define 
`HOST_CC="clang -..." waf configure`  environment variables.

**Comment by rpuntaie** [comment]
For later maybe WAF can support cross compilation in a more fundamental way, i.e. via the actual tool files like `gcc.py`, `gxx.py` , `gas.py`, ...

**Pull request merged**
