### PR TITLE
Extend check_swig_version

### PR DESCRIPTION
**Pull request by danbar**
Extend check_swig_version in order to behave similar to check_python_version.

### CODE REVIEW

**Comment by ita1024** [comment]
If Swig is too old, then the version will always be green, never yellow.

**Comment by ita1024** [comment]
Looks like copy-paste :-) Can you update the pull request with the fix above so that the correct message is displayed at least?

**Comment by danbar** [comment]
You are right :-). I have updated the pull request.

**Comment by ita1024** [comment]
I want to apply the changes to the branch 1.8 as well, is there any chance to get this as a single commit? Else I will have to merge by hand :-(

**Comment by ita1024** [comment]
Looks like I will have to merge this by hand

**Comment by danbar** [comment]
Sorry, I have read your comment a bit too late.

**Pull request merged**
