### PR TITLE
Make D dependency scanner aware of package.d files

### PR DESCRIPTION
**Pull request by SirNickolas**
When importing `path.to.module` in D, both `path/to/module.d` and `path/to/module/package.d` should be tried.

### CODE REVIEW

**Comment by ita1024** [comment]
A minimal example is needed, can you please provide one file or two for `demos/d` that shows how the dependency must be obtained?

**Comment by ita1024** [comment]
I wish you could provide an example :-/

**Comment by SirNickolas** [comment]
Sorry, I was fighting the errors while trying to make compilation with headers (.di) work. It came out that the D compiler had a [bug](https://issues.dlang.org/show_bug.cgi?id=15676) in it.

I'll provide full D support (as much as it can be done for now) in a few days. Sorry again for the inconvenience.

**Comment by ita1024** [comment]
This is unclear. If you do not provide the example I am afraid that I will have to revert the change.

**Comment by SirNickolas** [comment]
When I finish, there are examples for every use case. However, you can revert it for now.

**Pull request merged**
