### PR TITLE
qt5: Workaround for QT5 detection on macOS (Bug #1910)

### PR DESCRIPTION
**Pull request by cawka**

### CODE REVIEW

**Comment by ita1024** [comment]
Could we leave the regexp as `re_qt = re.compile(pat % '(?P<name>Qt5.*)' + '$')` ? What is the reason to remove Qt5 from the name and add it again?

**Comment by ita1024** [comment]
@fedepell ^^

**Comment by cawka** [comment]
I described the issue in the bug #1912.  There is no "5" in the framework name, unfortunately.

**Comment by ita1024** [comment]
Yes, thank you.

**Comment by fedepell** [comment]
Sorry for the late response. 

Looks awkward that they adapt a quite random library naming scheme :/ But if it is so I guess it is correct then to put the different regex (either just for macOS or in general)

**Comment by ita1024** [comment]
@fedepell :+1:

**Pull request merged**
