### PR TITLE
Xcode6 updates

### PR DESCRIPTION
**Pull request by mimon**
Fixes a bug where XCode would crash when generated by xcode6 tool combined with the c_config tool. The xcode6 merges the entire conf.env into XCode and the crash occurred if any value of the conf.env was a dictionary (XCode does not allow dictionary types in the build settings tree).

### CODE REVIEW

**Comment by ita1024** [comment]
This will fail on Python 3 (`RuntimeError: dictionary changed size during iteration`)

**Comment by ita1024** [comment]
The reason for removing `conf.env.ARCHS = 'x86_64'` from the example is unclear. Do you mean this should never be set or that this should be undocumented?

**Comment by mimon** [comment]
argh, i was afraid of that .. let me fix it! Do you want a new PR?

"The reason for removing conf.env.ARCHS = 'x86_64' from the example is unclear. Do you mean this should never be set or that this should be undocumented?"
Sorry, it was a bit unclear yes. I removed it because I thought I'd be better not to limit the generated XCode project example to x86_64. But, at second thought, it might be better to that at a later time when I have a complete iOS / ARM examples ready (which is in my TODO).

**Comment by mimon** [comment]
Closing and making new PR.

**Comment by ita1024** [comment]
Squash your commits and update the PR. Removing ARCHS from the example looks incorrect, if this has an effect, comment the line out and add a comment in the code that explains the valid values and the effect.

**Pull request closed without merging**
