### PR TITLE
When '--top' is specified there is no reason to climb

### PR DESCRIPTION
**Pull request by captainmalloc**
All in title.

### CODE REVIEW

**Comment by ita1024** [comment]
I am not sure I understand: if `top` is set then the inside of the loop `while cur and not Context.top_dir` is never reached.

Could you elaborate or perhaps produce a test in:
https://github.com/waf-project/waf/blob/waf-2.0/tests/init/wscript#L121

**Comment by captainmalloc** [comment]
Sorry about that, I forgot to remove that part of the `while` condition. 

My idea is to discover is lockfile exists even if the `--top` option has been defined. With this  previous `Context.out_dir` can be restored, if a lock file exists. Does it make sense?

**Comment by ita1024** [comment]
In this case `start_dir` is also affected. Two tests were added to account for that.

**Comment by ita1024** [comment]
Please update your copy and try it.

**Comment by captainmalloc** [comment]
Everything seems to work fine, thanks for merging this

**Pull request merged**
