### PR TITLE
Fix breaking changes from #1939 where target 'MyExe' was unable to build in XCode

### PR DESCRIPTION
**Pull request by mimon**
In playground/xcode6/wscript: Target 'MyExe' was declared before dependency target 'MyDynLib'.

This caused the generated XCode project to not be able to build 'MyExe' since 'MyDynLib' could not be added as a dependency in the XCode project.

### CODE REVIEW

**Comment by ita1024** [comment]
This is strange, the non-xcode build correctly sets the dependency on the lib from the exe. Is there something assuming an order of target declaration in the xcode tool?

**Comment by mimon** [comment]
Yes. It loops all TaskGenerators and then for each taskgen it does the following dependency check:

```python
# Check if any framework/lib to link against is some other target we've made
libs = getattr(tg, 'tmp_use_seen', [])
for lib in libs:
	use_target = p.get_target(lib)
        if should_add_to_xcode:
            ...
```

I guess the better solution is to put that dependency check after all taskgens have been processed, and then add any dependency chain to the project file. But that requires some refactoring which I don't have time for atm.

**Comment by ita1024** [comment]
Can you try the changes above? The target declaration order should not have any impact.

**Comment by mimon** [comment]
Yes, it (d300a7c) builds correctly! 👍

**Comment by ita1024** [comment]
Closing this then.

**Pull request closed without merging**
