### PR TITLE
Include stddef.h in SNIP_FIELD

### PR DESCRIPTION
**Pull request by selsky**
Make sure that size_t is defined per GitHub issue #1905

### CODE REVIEW

**Comment by ita1024** [comment]
No, we cannot do that.

If you want a header for all configuration tests, first make sure it is actually present and has `conf.check(header_name=['stddef.h'], auto_add_header_name=True)` (or set the list `conf.env.include_key')

**Comment by selsky** [comment]
Since size_t is used in the snip itself, shouldn't the snip be responsible for including any required headers?  Or should the snip avoid using size_t since some platforms don't define size_t unless you explicitly include stddef.h or sys/types.h?

**Comment by ita1024** [comment]
Those headers may be missing from certain platforms, so it is up to the project to set a configuration test.

**Comment by selsky** [comment]
The compiler error isn't from the headers that I'm testing though.  It's from the snippet's code.2

Can we replace the last line of the snippet with "return 0"?  Or is it critical to check that off < sizeof()?

**Comment by ita1024** [comment]
Yes, you are right in the sense that the test is most likely going to only succeed on some platforms. If we make changes then we need to turn this into a chain of tests. I believe that the test code is just too complicated and the `type_name`/`field_name` should never be there in the first place (will be removed in waf 2.0).

No we cannot replace the last line: the compiler might optimize the code and render the test ineffective.

**Comment by JPEWdev** [comment]
So what's the recommended migration strategy if you have a project that was using one of these checks (I'm particularly interested in function_name)?

**Comment by ita1024** [comment]
@JPEWdev pass the test code as `fragment=` parameter:

https://github.com/selsky/waf/blob/8deaa2bac0c653be8c5406cab969bc03ec8c02de/waflib/Tools/c_config.py#L55

**Pull request closed without merging**
