### PR TITLE
Detect architecture-specific library path for Boost on dpkg-based systems

### PR DESCRIPTION
**Pull request by eric135**

### CODE REVIEW

**Comment by ita1024** [comment]
1. `subprocess.check_output` is not present in Python 2.5-2.6.
2.  there are encoding concerns in Python 3

Could you try `conf.cmd_and_log(['ls'])`? I could update the changes but I have no system to test the resulting code. Thank you!

**Comment by eric135** [comment]
@ita1024 `self.cmd_and_log(['ls'])` saves the output of ls to build/config.log

**Comment by eric135** [comment]
I modified the commit and now it should work on Python 2.5-2.6 (my system runs 2.7 so I wasn't able to test it).

**Comment by ita1024** [comment]
1. Have you tried on Python3?
2. The point is precisely to leave a trace in `config.log`, but this can be disabled if deemed necessary. What would be the reason to not have it?

**Comment by eric135** [comment]
I added the `config.log` trace and modified the latest version to also work under Python3. I verified on Python 3.6.3.

**Comment by ita1024** [comment]
Apologies for the confusion! A single line is all that is needed!
```python
deb_host_multiarch = self.cmd_and_log([self.env.DPKG_ARCHITECTURE[0], '-qDEB_HOST_MULTIARCH'])
```

**Comment by ita1024** [comment]
Please update your copy and try https://github.com/waf-project/waf/commit/bef6f1b4bfe5527cbfad550b46bedb7e2a3c1352

**Comment by eric135** [comment]
I copied the changes from bef6f1b into one of my projects using waf and it detected the architecture-specific Boost install using both Python2 and Python3.

**Comment by ita1024** [comment]
Thank you!

**Pull request merged**
