### PR TITLE
Extended playground use example

### PR DESCRIPTION
**Pull request by daniel-brosche**
Related to https://github.com/waf-project/waf/issues/2035

### CODE REVIEW

**Comment by ita1024** [comment]
Can you briefly describe what that example is supposed to show and why we are supposed to have it? Thanks.

**Comment by daniel-brosche** [comment]
It extends the use example with some more complexity which means it recurses another hierachy down and extends the dependency graph. 
My main idea was to provide this code for reproduction and regression testing.
I have noticed that there is still a comment in the code that could be removed before merging.

Are you interested in more playground examples?

I have also some another scenarios that are maybe interesting (as mentioned more complex multiproject scenarios).

**Comment by ita1024** [comment]
I am not particularly interested into more examples unless they have good quality as this means more maintenance.

**Comment by daniel-brosche** [comment]
I understand, I will create some templates and store them in my repository. Maybe you can reference them later on your website.

**Pull request merged**
