### PR TITLE
pytest: Added better support for normal and pyext library dependencies.

### PR DESCRIPTION
**Pull request by xbreak**
This also includes the `buildcopy` feature that allows construction of complete Python packages in the build dir.

See `playground/pytest/wscript` for use-cases and #2017 for motivation why `buildcopy` was needed.

### CODE REVIEW

**Comment by ita1024** [comment]
There is already a task generator method called `to_nodes`. Be careful with `shutil.copy2` and opening/closing files in `Python < 3.6`; prefer `Utils.readf/writef` instead.

**Comment by xbreak** [comment]
Thanks!

I found another corner case for `pytest` to handle, so while I'm fixing that I'll also rename `to_nodes` to `to_src_nodes` to avoid any confusion.

Regarding `shutil.copy2` I'm not familiar with the risks you seem to be referring to, could you clarify?

**Comment by ita1024** [comment]
File handles are opened exclusively and inherited. If a file is being written while other tasks are running, then those may prevent the file from being read by other processes.

**Comment by xbreak** [comment]
For reference, this seems to cover the info about the issue:
- [Issue 17634: Win32: shutil.copy leaks file handles to child processes](https://bugs.python.org/issue17634) and
- [PEP 446 -- Make newly created file descriptors non-inheritable](https://www.python.org/dev/peps/pep-0446/)

Since `Utils.readf/writef` puts the whole file in memory I started writing a `Utils.copyfile` function which use bounded memory instead. Now, it would be nice if file attributes were preserved during the copy, but here it seems like there's no reasonable way to do that using file descriptors opened with `os.O_NOINHERIT` (the `shutils.copystat` function seem very messy to implement in a portable way).
On the other hand, for the `buildcopy` use case I don't think the attributes are important unless those files are accidentally picked up by `<task_gen>.to_nodes` somewhere.

At the same time the same general problem with inherited FDs seem to be around in other places as well in waf (the install tasks and file attribute modifications for example) so if it's really a problem we want to solve then it's going to impact other places as well.

Reading tickets about the issue it seems most likely to impact you if a subprocess holds a file handle to something in a directory which some other process tries to delete. Is this likely to happen? Not in the `buildcopy` use case I think.

**Pull request merged**
