### PR TITLE
Optionally lazily check installed msvc compilers' environments

### PR DESCRIPTION
**Pull request by shoover**
and stop when one is found that matches the user's options. This happens during autodetect only
when the new option msvc_lazy_autodetect or env.MSVC_LAZY_AUTODETECT is set.

These version uses a lazytup class modified from Thomas in an effort to not break all the gather* APIs. Because these get saved in the config set, repr is overridden to display the real tuple value for targets that have been evaluated and a default value for those that have not.

### CODE REVIEW

**Comment by ita1024** [comment]
How about reading `conf.options.msvc_lazy_autodetect or conf.env.MSVC_LAZY_AUTODETECT` instead of passing the `lazy` parameter in every method? I am not sure anyone will want to pass lazy to some methods but not to others.

If you do not provide an update I can merge the pull request and refactor this afterwards.

**Comment by shoover** [comment]
No problem, I will update it.

**Comment by shoover** [comment]
This has been tested with winphone, wsdk, wince, and msvc. Is there anyone available who can test intel?

**Comment by che2** [comment]
+1 Thanks for submitting this patch. 
With 3 versions of Visual Studio installed, my project configuration time on Windows went down to about 3 seconds from about 30.
 
I suggest making `--msvc-lazy-autodetect` the default option if the `--msvc-version` option is also set. It doesn't make sense for the user to wait until all versions of Visual Studio installed on the system has been tested if he already knows the version that he wants to use.

**Comment by ita1024** [comment]
We will make this the default option in Waf 1.9

**Comment by che2** [comment]
Thanks!

**Comment by srouquette** [comment]
Thanks for this patch!  :D

**Pull request merged**
