### PR TITLE
swig tool can handle -outdir parameter

### PR DESCRIPTION
**Pull request by yag00**
Swig tool can easily handle swig -outdir parameter with this patch

### CODE REVIEW

**Comment by ita1024** [comment]
Why is this necessary once again?

**Comment by yag00** [comment]
Not necessary but it's easier to generate file where you want them instead of doing some copy after generation.

**Comment by ita1024** [comment]
There was a TODO note concerning this. How do you use it (it would be best if we had a testcase in playground/swig), and on which operating systems have you used it?

**Comment by yag00** [comment]
I tested it on Ubuntu 14.04 and Fedora 20 64bit. I just commited the updated playground/swig test case in my master branch.  Work with both block case...

**Comment by ita1024** [comment]
We will have to try on windows systems.

**Pull request merged**
