### PR TITLE
vala: Initialize 'VALAFLAGS' with OS flags

### PR DESCRIPTION
**Pull request by arteymix**

### CODE REVIEW

**Comment by ita1024** [comment]
I am really unsure about `self.env.append_unique('VALAFLAGS', ['-C'])`. If the vala flags are provided in the environment, why change them?

**Comment by arteymix** [comment]
The tool essentially rely on C code generation (triggered by the `-C` flag). It might be nicer to put that into the task though.

The reason OS flags are applied is because it's handy to pass `--debug` or `--vapi-comments` flags to customize the build.

**Comment by ita1024** [comment]
I missed the `append_unique` there. Looks good!

**Comment by arteymix** [comment]
Nice, thanks, this is a game changer for me!

**Pull request merged**
