### PR TITLE
Allow install_path to be None when building python code

### PR DESCRIPTION
**Pull request by selsky**
demos/python/wscript has:
```
        # first compile a few pyc and pyo files (set install_path=None to disable the installation,
        # by default install_path is set to ${PYTHONDIR})
```
but if you try that:
```
$ cat wscript 
def options(opt):
    opt.load('python')

def configure(conf):
    conf.load('python')
    conf.check_python_version()

def build(bld):
    bld(features='py', source=bld.path.ant_glob('*.py'), install_path=None)
```
the result is:
```
$ ./waf configure
Setting top to                           : /Users/selsky/src/github.com/waf/demos/python 
Setting out to                           : /Users/selsky/src/github.com/waf/demos/python/build 
Checking for program 'python'            : /usr/bin/python 
Checking for python version              : 2.7.10 
'configure' finished successfully (0.228s)
$ ./waf build
Waf: Entering directory `/Users/selsky/src/github.com/waf/demos/python/build'
Waf: Leaving directory `/Users/selsky/src/github.com/waf/demos/python/build'
Traceback (most recent call last):
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Scripting.py", line 118, in waf_entry_point
    run_commands()
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Scripting.py", line 178, in run_commands
    ctx=run_command(cmd_name)
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Scripting.py", line 169, in run_command
    ctx.execute()
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Scripting.py", line 366, in execute
    return execute_method(self)
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Build.py", line 93, in execute
    self.execute_build()
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Build.py", line 100, in execute_build
    self.compile()
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Build.py", line 167, in compile
    self.producer.start()
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Runner.py", line 214, in start
    self.refill_task_list()
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Runner.py", line 135, in refill_task_list
    tasks=self.biter.next()
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Build.py", line 402, in get_build_iterator
    self.post_group()
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Build.py", line 385, in post_group
    tgpost(tg)
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Build.py", line 359, in tgpost
    f()
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/TaskGen.py", line 123, in post
    v()
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/TaskGen.py", line 247, in process_source
    self.get_hook(node)(self,node)
  File "/Users/selsky/src/github.com/waf/.waf-2.0.2-69b89968fa766146a28a37d95f32f798/waflib/Tools/python.py", line 47, in process_py
    assert(getattr(self,'install_path')),'add features="py"'
AssertionError: add features="py"
```

### CODE REVIEW

**Comment by ita1024** [comment]
Removing the asssertion will produce `AttributeError: 'task_gen' object has no attribute 'install_path'` for `source='foo.py')` so we cannot apply this. Try the change made upstream?

**Comment by selsky** [comment]
That works for me.  Can you backport to 1.9 as well?

Should the assertion error message be more descriptive and refer to install_path? Also, what's the intention of the install_path check on line 85?

**Comment by selsky** [comment]
Which line produced the AttributeError exception?

**Comment by selsky** [comment]
Also, doesn't line 64 ensure that install_path will always return true for hasattr()?
```
        self.install_path = getattr(self, 'install_path', '${PYTHONDIR}')
```

**Comment by ita1024** [comment]
Line 85 raises an AttributeError exception when `features='py'` is not provided.

**Pull request closed without merging**
