### PR TITLE
Correction of boost module detection of Boost.Log

### PR DESCRIPTION
**Pull request by cawka**
The previous logic in #1709 made an incorrect assumption that the filename of shared/static library indicates that it was build as multi-threaded or single threaded.  This assumption does not hold in many Linux distributions.

In addition to that. Boost.Thread and Boost.Log require -pthread (or some other) flags in order to properly link.

### CODE REVIEW

**Comment by ita1024** [comment]
Please update the pull request with `env.append_value` instead of in-place value modifications:

```python
        v = conf.env
        conf.env.CFLAGS = ['-O2']
        conf.env = conf.env.derive()
        conf.env.stash()
        # contrast with conf.env.append_value('CFLAGS', '-O3')
        conf.env.CFLAGS += ['-O3']
        conf.env.revert()
        print(conf.env.CFLAGS, v.CFLAGS)
```

**Comment by brettviren** [comment]
Maybe related, in waf 1.8.20 (and also 1.8.13) building against Boost 1.60.0 I get a configure failure on Ubuntu 15.10.

```
Checking boost includes                                                                                                                                          : 1.60.0 
	path : /opt/bv/projects/wire-cell/wire-cell-spack/spack/opt/spack/linux-x86_64/gcc-5.2.1/boost-1.60.0-xwkgkiyjfqsmznia62oye5suvpcur5em/include 
Checking boost libs                                                                                                                                              : ok 
	path : /opt/bv/projects/wire-cell/wire-cell-spack/spack/opt/spack/linux-x86_64/gcc-5.2.1/boost-1.60.0-xwkgkiyjfqsmznia62oye5suvpcur5em/lib 
	shared libs : ['boost_system', 'boost_filesystem', 'boost_graph', 'boost_thread-mt.so.1.60', 'boost_program_options'] 
	static libs : [] 
Checking for boost linkage                                                                                                                                       : 18:48:16 runner ['/usr/bin/g++', '--std=c++11', '-fPIC', '-I/opt/bv/projects/wire-cell/wire-cell-spack/spack/opt/spack/linux-x86_64/gcc-5.2.1/boost-1.60.0-xwkgkiyjfqsmznia62oye5suvpcur5em/include', '-DHAVE_EIGEN_DENSE=1', '../test.cpp', '-c', '-o', '/tmp/bv/spack-stage/spack-stage-mlW072/wire-cell-build/build/.conf_check_97e4a6c003375de786268e41ab780944/testbuild/test.cpp.1.o']
18:48:16 runner ['/usr/bin/g++', 'test.cpp.1.o', '-o', '/tmp/bv/spack-stage/spack-stage-mlW072/wire-cell-build/build/.conf_check_97e4a6c003375de786268e41ab780944/testbuild/testprog', '-Wl,-Bstatic', '-L/opt/bv/projects/wire-cell/wire-cell-spack/spack/opt/spack/linux-x86_64/gcc-5.2.1/boost-1.60.0-xwkgkiyjfqsmznia62oye5suvpcur5em/lib', '-Wl,-Bdynamic', '-L/opt/bv/projects/wire-cell/wire-cell-spack/spack/opt/spack/linux-x86_64/gcc-5.2.1/boost-1.60.0-xwkgkiyjfqsmznia62oye5suvpcur5em/lib', '-lboost_system', '-lboost_filesystem', '-lboost_graph', '-lboost_thread-mt.so.1.60', '-lboost_program_options']
Could not link against boost libraries using supplied options 
```
The Boost thread libraries are built from source (not system packages) and are spelled like:

```
libboost_thread-mt.a
libboost_thread-mt.so
libboost_thread-mt.so.1.60.0
```
So, either the thread library needs that final `.0` or it needs to be versionless like the other libs.  

HTH.

**Comment by ita1024** [comment]
@cawka: any update or you are expecting me to rewrite this?
@brettviren: yes?

**Comment by ita1024** [comment]
I am not going to merge this, if you still think there is something to do, open a new pull request

**Comment by ryobg** [comment]
Hello @cawka, have you considered to finnish your work on this patch?

Just for the record: I ran into the same issue and now I use the proposed patch/version instead of the Waflib's Boost one. I suppose other people are meeting the same issue. I would gladly contribute it, but it was not made by me.

**Pull request closed without merging**
