### PR TITLE
Fix building shared libraries with -fPIE

### PR DESCRIPTION
**Pull request by rlaager**
I'm seeing this with NTPsec, which uses waf to build.

Debian wants to build with -fPIE for security reasons.  This is not compatible with building shared libraries like the ntpc python extension.  If the -fPIE flag comes before -shared (or -fPIC), the latter will override, and the build succeeds.

### CODE REVIEW

**Comment by rlaager** [comment]
NTPsec is reporting these flags:
  LDFLAGS                       :  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -lbsd -lssp_nonshared -Wl,-z,now -Wl,-z,relro 
  LINKFLAGS_NTPD                :  -pie

**Comment by ita1024** [comment]
Such a change cannot be applied because it would break a lot of other projects. Could you add your flags to LINKFLAGS instead, for example `LINKFLAGS=-fpie waf configure build`?

**Comment by rlaager** [comment]
LDFLAGS is a pretty standard name for such things. But yes, it seems to work with:
`LINKFLAGS='$(LDFLAGS)' LDFLAGS='' python waf configure ...`

**Comment by ita1024** [comment]
The matter seems to be answered, closing this now.

**Pull request closed without merging**
