### PR TITLE
fix potential concurrency issue for Waf tool cpplint if using parallel jobs

### PR DESCRIPTION
**Pull request by danbar**
If parallel jobs are used for the Waf tool cpplint, a potential concurrency issue is triggered.
The reason seems to be that the function ProcessFile (file waflib/extras/cpplint.py, line 205) shares the global module state _cpplint_state (file waflib/extras/cpplint.py, line 200) across parallel jobs.

### CODE REVIEW

**Comment by ita1024** [comment]
If there are multiple cpplint tasks, then such tasks will all inherit the same data from the last version of self.env.CPPLINT_FILTERS found?

**Comment by danbar** [comment]
As far as I understood, each cpplint task should get the same version of self.env.CPPLINT_FILTERS. 
The problem seems to be that ProcessFile is changing the filters in _cpplint_state. If multiple tasks are running concurrently, they are potentially influencing each other. I was able to resolve this issue in our project by shifting the line _cpplint_state.SetFilters(self.env.CPPLINT_FILTERS) to the constructor.

**Comment by ita1024** [comment]
`self.env.CPPLINT_FILTERS` is not necessarily the same for each cpplint task.

**Comment by danbar** [comment]
Would it have any influence, if self.env.CPPLINT_FILTER is different for each cpplint task?
I think the (potential) problem is that _cpplint_state.SetFilters(self.env.CPPLINT_FILTERS) is located in the run method and not in the constructor. Or am I missing something here?

**Comment by ita1024** [comment]
Yes, it will: the state will be set by the most recently created task.

**Comment by danbar** [comment]
Ok, I understand. But the state is anyhow shared across tasks, because _cpplint_state is a global state of the module. Please see line 848 in https://github.com/google/styleguide/blob/gh-pages/cpplint/cpplint.py

**Comment by ita1024** [comment]
The build order is therefore incorrect and the change suggested should not be applied.

**Comment by danbar** [comment]
I agree. The thing is that I observed that the build order influences cpplint in the sense that the filters get "corrupted" if I am using parallel jobs. The (potential) explanation was that ProcessFile shares a global module state, which is changed during the function call.

**Comment by ita1024** [comment]
Try 33c72e06915d7f40df33ccb639beda9d3b11208a

**Comment by danbar** [comment]
Thx. I will try it out tomorrow and will let you know if it works out.

**Comment by danbar** [comment]
Tried it out and seems to work!

**Pull request closed without merging**
